version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar
