logger:
  level: info
  file: /dev/stdout

storage:
  type: memory
  database:
    host: localhost
    port: 5432
    user: calendar
    password: calendar
    db: calendar

server:
  http:
    host: localhost
    port: 8090
  grpc:
    host: localhost
    port: 8080
